blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .forms import PostForm
from .models import Post


# Create your views here.
def post_list(request):
    posts = (
        getattr(Post, 'objects')
        .filter(published_date__lte=timezone.now())
        .order_by('published_date')
    )
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

blog/templates/blog/master.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'gto/img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
    {% block extra_head %}{% endblock %}
</head>
<body>
    <header class="page-header">
        <div class="container">
            <a href="{% url 'blog:post_new' %}" class="top-menu">
                {% include './svg/file-earmark-plus.svg' %}
            </a>
            <h1><a href="/">{% block extra_title %}{% endblock %}</a></h1>
        </div>
    </header>
    <main class="container">{% block content %}{% endblock %}</main>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends "blog/master.html" %}
{% block title %}Блог Django Girls{% endblock %}
{% block extra_title %}Блог Django Girls{% endblock %}
{% block content %}
  <div class="row">
    <div class="col">
      <article class="post">
        {% if post.published_date %}
          <time class="date">
              {{ post.published_date }}
          </time>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
      </article>
    </div>
  </div>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "blog/master.html" %}
{% block title %}Блог Django Girls{% endblock %}
{% block extra_title %}Блог Django Girls{% endblock %}
{% block content %}
    <div class="row">
        <div class="col">
            {% for post in posts %}
                <article class="post">
                    <time class="date">
                        {{ post.published_date }}
                    </time>
                    <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
                    <p>{{ post.text|linebreaksbr }}</p>
                </article>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

blog/templates/blog/post_new.html
{% extends "blog/master.html" %}
{% block title %}Блог Django Girls{% endblock %}
{% block extra_title %}Блог Django Girls{% endblock %}
{% block content %}
<div class="row">
  <div class="col">
    <h2>New post</h2>
    <form method="POST" class="post-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
  </div>
</div>
{% endblock content %}